dependencies:
  - name: nginx-ingress
    version: 0.31.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nginx-ingress.enabled
  - name: traefik
    version: 1.61.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: traefik.enabled    