# Default values for whoami.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bee42/whoami
  tag: multiarch
  pullPolicy: IfNotPresent
  pullSecret:
    name: whoami
    enabled: false

imageCredential:
  registry: r-gitlab.bee42.com
  username: xxxx
  password: xxxx

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  path: /
  hosts:
    -  whoami.bee42.192.168.42.32.nip.io
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  annotations:
    kubernetes.io/ingress.class: traefik 

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
labels:
  blinkt: show
  blinktColor: 00FF00

nodeSelector: {}

tolerations: []

affinity: {}

nginx-ingress:
  enabled: false
  controller.metrics.enabled: true
  rbac.create: true
  ssl-redirect: false
  controller.service.type: NodePort
  controller.service.nodePorts.http: 30180

traefik:
  enabled: false
  serviceType: NodePort
  imageTag: 1.7.9
  rbac:
    enabled: true
  dashboard:
    enabled: true
  accessLogs:
    enabled: true
  debug:
    enabled: true
  ssl:
    enabled: false
    enforced: false
  acme:
    enabled: false
  metrics:
    prometheus:
      enabled: true