apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: whoami
spec:
  selector:
    matchLabels:
      app: whoami
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: bee42/whoami:1.2.0
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
          name: http
